#!/usr/bin/python3
import sys
import os
import subprocess
import json
from pprint import pprint

stdin = sys.stdin.read()

params = json.loads(stdin)
#pprint(params, stream=sys.stderr)

version = params.get('version', { 'ref': 'none'})

output = {"version": version}

print(json.dumps(output))
